"use client";

export default function PaymentReceipt({
  open,
    amount,
      recipient,
        hash,
          onClose,
          }) {
            if (!open) return null;

              const shortAddress = (address) =>
                  address
                        ? `${address.slice(0, 6)}...${address.slice(-4)}`
                              : "";

                                const copyHash = async () => {
                                    if (!hash) return;

                                        try {
                                              await navigator.clipboard.writeText(hash);
                                                    alert("Transaction hash copied!");
                                                        } catch {
                                                              alert("Unable to copy transaction hash.");
                                                                  }
                                                                    };

                                                                      return (
                                                                          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4">
                                                                                <div className="w-full max-w-md rounded-3xl border border-zinc-800 bg-zinc-900 p-6">

                                                                                        <div className="text-center">
                                                                                                  <div className="mb-4 text-6xl">✅</div>

                                                                                                            <h2 className="text-2xl font-bold text-white">
                                                                                                                        Payment Successful
                                                                                                                                  </h2>

                                                                                                                                            <p className="mt-2 text-zinc-400">
                                                                                                                                                        {amount} USDC Sent
                                                                                                                                                                  </p>
                                                                                                                                                                          </div>

                                                                                                                                                                                  <div className="mt-8 space-y-5">

                                                                                                                                                                                            <div>
                                                                                                                                                                                                        <p className="text-sm text-zinc-500">
                                                                                                                                                                                                                      Recipient
                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                              <p className="mt-1 font-semibold text-white">
                                                                                                                                                                                                                                                            {shortAddress(recipient)}
                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                        <p className="text-sm text-zinc-500">
                                                                                                                                                                                                                                                                                                                      Transaction Hash
                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                              <p className="mt-1 break-all text-sm text-white">
                                                                                                                                                                                                                                                                                                                                                            {hash}
                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mt-8 space-y-3">

                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={copyHash}
                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full rounded-xl bg-yellow-400 py-3 font-semibold text-black hover:bg-yellow-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                          Copy Transaction Hash
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          href={`https://testnet.arcscan.app/tx/${hash}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="block w-full rounded-xl bg-zinc-800 py-3 text-center font-semibold text-white hover:bg-zinc-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    View on ArcScan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={onClose}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full rounded-xl border border-zinc-700 py-3 font-semibold text-white hover:bg-zinc-800"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Done
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }