"use client";

import { useEffect, useRef } from "react";
import { isAddress } from "viem";

export default function QRScanner({
  open,
    onClose,
      onScan,
      }) {
        const scannerRef = useRef(null);

          useEffect(() => {
              if (!open) return;

                  let cancelled = false;

                      async function startScanner() {
                            try {
                                    // Lazy-load html5-qrcode
                                            const { Html5Qrcode } = await import("html5-qrcode");

                                                    if (cancelled) return;

                                                            const html5QrCode = new Html5Qrcode("reader");
                                                                    scannerRef.current = html5QrCode;

                                                                            const cameras = await Html5Qrcode.getCameras();

                                                                                    if (!cameras.length) {
                                                                                              alert("No camera found.");
                                                                                                        return;
                                                                                                                }

                                                                                                                        // Prefer back camera
                                                                                                                                const camera =
                                                                                                                                          cameras.find((c) =>
                                                                                                                                                      c.label.toLowerCase().includes("back")
                                                                                                                                                                ) || cameras[cameras.length - 1];

                                                                                                                                                                        await html5QrCode.start(
                                                                                                                                                                                  camera.id,
                                                                                                                                                                                            {
                                                                                                                                                                                                        fps: 10,
                                                                                                                                                                                                                    qrbox: {
                                                                                                                                                                                                                                  width: 250,
                                                                                                                                                                                                                                                height: 250,
                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                async (decodedText) => {
                                                                                                                                                                                                                                                                                            let value = decodedText.trim();

                                                                                                                                                                                                                                                                                                        if (value.startsWith("ethereum:")) {
                                                                                                                                                                                                                                                                                                                      value = value.replace("ethereum:", "");
                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                              if (!isAddress(value)) {
                                                                                                                                                                                                                                                                                                                                                            alert("❌ Invalid wallet QR code.");
                                                                                                                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                                await html5QrCode.stop();
                                                                                                                                                                                                                                                                                                                                                                                                                            } catch {}

                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      await html5QrCode.clear();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch {}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              scannerRef.current = null;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onScan(value);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              () => {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error(err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert("Unable to start camera.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          startScanner();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cancelled = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (scannerRef.current) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  scannerRef.current
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .stop()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .catch(() => {})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .then(() => scannerRef.current?.clear())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .catch(() => {});

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  scannerRef.current = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }, [open, onScan]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!open) return null;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div className="w-full max-w-md rounded-3xl border border-zinc-700 bg-zinc-900 p-5">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div className="mb-5 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <h2 className="text-xl font-bold text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Scan Wallet QR
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={onClose}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           className="h-10 w-10 rounded-xl bg-zinc-800 text-white hover:bg-zinc-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ✕
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    id="reader"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="overflow-hidden rounded-2xl"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <p className="mt-4 text-center text-sm text-zinc-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Scan an Arc / Ethereum wallet QR code only.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }