"use client";

import QRCode from "react-qr-code";
import { Copy, Share2, X } from "lucide-react";

export default function ReceiveModal({
  open,
    address,
      onClose,
      }) {
        if (!open) return null;

          const copyAddress = async () => {
              try {
                    await navigator.clipboard.writeText(address);
                          alert("✅ Wallet address copied!");
                              } catch {
                                    alert("❌ Unable to copy address.");
                                        }
                                          };

                                            const shareAddress = async () => {
                                                if (!navigator.share) {
                                                      alert("❌ Sharing isn't supported on this device.");
                                                            return;
                                                                }

                                                                    try {
                                                                          await navigator.share({
                                                                                  title: "FlashTap Wallet",
                                                                                          text: `Send USDC to my FlashTap wallet:\n\n${address}`,
                                                                                                });

                                                                                                      alert("✅ Wallet shared successfully!");
                                                                                                          } catch {
                                                                                                                alert("❌ Share cancelled.");
                                                                                                                    }
                                                                                                                      };

                                                                                                                        return (
                                                                                                                            <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">

                                                                                                                                  <div className="relative w-full max-w-md rounded-3xl border border-zinc-800 bg-zinc-900 p-6 shadow-2xl">

                                                                                                                                          {/* Close Button */}

                                                                                                                                                  <button
                                                                                                                                                            onClick={onClose}
                                                                                                                                                                      className="absolute right-5 top-5 rounded-xl bg-zinc-800 p-2 text-white transition hover:bg-zinc-700"
                                                                                                                                                                              >
                                                                                                                                                                                        <X size={18} />
                                                                                                                                                                                                </button>

                                                                                                                                                                                                        {/* Header */}

                                                                                                                                                                                                                <div className="text-center">
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                  <h2 className="text-3xl font-bold text-white">
                                                                                                                                                                                                                                                                                              Receive Payments
                                                                                                                                                                                                                                                                                                        </h2>

                                                                                                                                                                                                                                                                                                                  <div className="mt-4 inline-flex rounded-full bg-green-500/10 px-4 py-2 text-sm font-semibold text-green-400">
                                                                                                                                                                                                                                                                                                                              Arc Testnet • USDC
                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                  <p className="mt-4 text-zinc-400">
                                                                                                                                                                                                                                                                                                                                                              Share this QR code or your wallet address to receive payments.
                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                        {/* QR Code */}

                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-8 flex justify-center">

                                                                                                                                                                                                                                                                                                                                                                                                          <div className="rounded-3xl bg-white p-6 shadow-lg">

                                                                                                                                                                                                                                                                                                                                                                                                                      <QRCode
                                                                                                                                                                                                                                                                                                                                                                                                                                    value={address || ""}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  size={260}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Wallet Address */}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-8 rounded-2xl border border-zinc-700 bg-zinc-800 p-5">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-xs uppercase tracking-widest text-zinc-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Receiving Wallet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-3 break-all font-mono text-sm text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {address}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Buttons */}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-8 space-y-3">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={copyAddress}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="flex w-full items-center justify-center gap-2 rounded-2xl bg-yellow-400 py-3 font-semibold text-black transition hover:bg-yellow-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Copy size={18} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Copy Address
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={shareAddress}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="flex w-full items-center justify-center gap-2 rounded-2xl bg-zinc-800 py-3 font-semibold text-white transition hover:bg-zinc-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Share2 size={18} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Share Wallet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Footer */}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="mt-6 text-center text-sm text-zinc-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Only send{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="font-semibold text-yellow-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            USDC on Arc Testnet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                to this address.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }