"use client";

import { useEffect, useState } from "react";
import { useAccount } from "wagmi";

export default function RecentTransactions() {
  const { address, isConnected } = useAccount();

    const [mounted, setMounted] = useState(false);
      const [transactions, setTransactions] = useState([]);

        useEffect(() => {
            setMounted(true);
              }, []);

                useEffect(() => {
                    if (!mounted || !address) {
                          setTransactions([]);
                                return;
                                    }

                                        try {
                                              const storageKey = `flashtap-transactions-${address.toLowerCase()}`;
                                                    const stored = JSON.parse(localStorage.getItem(storageKey) || "[]");

                                                          // Remove duplicate transactions
                                                                const unique = Array.from(
                                                                        new Map(stored.map((tx) => [tx.hash, tx])).values()
                                                                              );

                                                                                    setTransactions(unique);
                                                                                        } catch {
                                                                                              setTransactions([]);
                                                                                                  }
                                                                                                    }, [mounted, address]);

                                                                                                      const shortenAddress = (addr) =>
                                                                                                          addr ? `${addr.slice(0, 6)}...${addr.slice(-4)}` : "";

                                                                                                            const formatTime = (timestamp) =>
                                                                                                                new Date(timestamp).toLocaleString([], {
                                                                                                                      dateStyle: "medium",
                                                                                                                            timeStyle: "short",
                                                                                                                                });

                                                                                                                                  if (!mounted) {
                                                                                                                                      return (
                                                                                                                                            <div className="mt-8 rounded-3xl border border-zinc-800 bg-zinc-900 p-5">
                                                                                                                                                    <h2 className="mb-5 text-lg font-bold uppercase tracking-wide text-white">
                                                                                                                                                              Recent Transactions
                                                                                                                                                                      </h2>

                                                                                                                                                                              <div className="rounded-2xl border border-zinc-700 bg-zinc-800 p-8 animate-pulse" />
                                                                                                                                                                                    </div>
                                                                                                                                                                                        );
                                                                                                                                                                                          }

                                                                                                                                                                                            return (
                                                                                                                                                                                                <div className="mt-8 rounded-3xl border border-zinc-800 bg-zinc-900 p-5">
                                                                                                                                                                                                      <h2 className="mb-5 text-lg font-bold uppercase tracking-wide text-white">
                                                                                                                                                                                                              Recent Transactions
                                                                                                                                                                                                                    </h2>

                                                                                                                                                                                                                          {!isConnected ? (
                                                                                                                                                                                                                                  <div className="rounded-2xl border border-dashed border-zinc-700 py-8 text-center text-zinc-500">
                                                                                                                                                                                                                                            Connect your wallet to view recent transactions.
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                          ) : transactions.length === 0 ? (
                                                                                                                                                                                                                                                                  <div className="rounded-2xl border border-dashed border-zinc-700 py-8 text-center text-zinc-500">
                                                                                                                                                                                                                                                                            No transactions yet.
                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                  <div className="space-y-4">
                                                                                                                                                                                                                                                                                                            {transactions.map((tx) => (
                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                      key={tx.hash}
                                                                                                                                                                                                                                                                                                                                                    className="rounded-2xl bg-zinc-800 p-4 transition hover:bg-zinc-700"
                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                <p className="font-semibold text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                    {tx.amount} USDC
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mt-1 text-sm text-zinc-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            To {shortenAddress(tx.recipient)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="mt-1 text-xs text-zinc-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {formatTime(tx.timestamp)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="rounded-full bg-green-500/20 px-3 py-1 text-xs font-semibold text-green-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Success
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {tx.hash && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href={`https://testnet.arcscan.app/tx/${tx.hash}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="mt-3 inline-block text-sm font-medium text-yellow-400 hover:underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              View on ArcScan →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }