"use client";

import { useAccount, useBalance } from "wagmi";
import { Copy, Wallet } from "lucide-react";

export default function WalletOverview({ onReceive }) {
  const { address, isConnected, status } = useAccount();

    const { data: balance, isLoading } = useBalance({
        address,
            watch: true,
                enabled: !!address,
                  });

                    const copyAddress = async () => {
                        if (!address) return;

                            try {
                                  await navigator.clipboard.writeText(address);
                                        alert("Wallet address copied!");
                                            } catch {
                                                  alert("Unable to copy wallet address.");
                                                      }
                                                        };

                                                          // Wait until wagmi finishes restoring the wallet
                                                            if (status === "connecting" || status === "reconnecting") {
                                                                return (
                                                                      <div className="mt-8 rounded-3xl border border-zinc-800 bg-zinc-900 p-6">
                                                                              <div className="h-40 animate-pulse rounded-2xl bg-zinc-800" />
                                                                                    </div>
                                                                                        );
                                                                                          }

                                                                                            if (!isConnected) {
                                                                                                return (
                                                                                                      <div
                                                                                                              suppressHydrationWarning
                                                                                                                      className="mt-8 rounded-3xl border border-zinc-800 bg-zinc-900 p-6 text-center"
                                                                                                                            >
                                                                                                                                    <Wallet className="mx-auto mb-4 h-10 w-10 text-yellow-400" />

                                                                                                                                            <h2 className="text-xl font-bold text-white">
                                                                                                                                                      No Wallet Connected
                                                                                                                                                              </h2>

                                                                                                                                                                      <p className="mt-2 text-zinc-400">
                                                                                                                                                                                Connect your wallet to view your balance and receive payments.
                                                                                                                                                                                        </p>
                                                                                                                                                                                              </div>
                                                                                                                                                                                                  );
                                                                                                                                                                                                    }

                                                                                                                                                                                                      return (
                                                                                                                                                                                                          <div
                                                                                                                                                                                                                suppressHydrationWarning
                                                                                                                                                                                                                      className="mt-8 rounded-3xl border border-zinc-800 bg-zinc-900 p-6"
                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                <div className="flex items-center justify-between">
                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                  <p className="text-sm uppercase tracking-widest text-zinc-400">
                                                                                                                                                                                                                                                              Connected Wallet
                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                  <h2 className="mt-2 text-lg font-semibold text-white">
                                                                                                                                                                                                                                                                                              {address?.slice(0, 6)}...{address?.slice(-4)}
                                                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                        <span className="rounded-full bg-green-500/20 px-4 py-2 text-sm font-semibold text-green-400">
                                                                                                                                                                                                                                                                                                                                  ● Connected
                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                      <div className="mt-8 rounded-2xl bg-black/30 p-5">
                                                                                                                                                                                                                                                                                                                                                              <p className="text-sm text-zinc-400">
                                                                                                                                                                                                                                                                                                                                                                        Available Balance
                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                        <h1 className="mt-2 text-4xl font-bold text-white">
                                                                                                                                                                                                                                                                                                                                                                                                  {isLoading
                                                                                                                                                                                                                                                                                                                                                                                                              ? "Loading..."
                                                                                                                                                                                                                                                                                                                                                                                                                          : `${Number(balance?.formatted ?? 0).toFixed(4)} ${balance?.symbol ?? "USDC"}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                  </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mt-6 flex gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={copyAddress}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="flex-1 rounded-xl border border-zinc-700 py-3 font-semibold text-white transition hover:border-yellow-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center justify-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Copy size={18} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Copy Address
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={onReceive}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="flex-1 rounded-xl bg-yellow-400 py-3 font-semibold text-black transition hover:bg-yellow-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Receive
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }