"use client";

import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useAccount, useBalance } from "wagmi";

export default function WalletCard() {
  const { address, isConnected } = useAccount();

    const { data: balance, isLoading } = useBalance({
        address,
            watch: true,
              });

                return (
                    <div className="flex justify-center mb-6">
                          <ConnectButton.Custom>
                                  {({
                                            account,
                                                      chain,
                                                                mounted,
                                                                          openConnectModal,
                                                                                    openAccountModal,
                                                                                              openChainModal,
                                                                                                      }) => {
                                                                                                                const ready = mounted;
                                                                                                                          const connected =
                                                                                                                                      ready &&
                                                                                                                                                  account &&
                                                                                                                                                              chain &&
                                                                                                                                                                          isConnected;

                                                                                                                                                                                    if (!connected) {
                                                                                                                                                                                                return (
                                                                                                                                                                                                              <button
                                                                                                                                                                                                                              onClick={openConnectModal}
                                                                                                                                                                                                                                              className="bg-blue-600 hover:bg-blue-700 px-5 py-2 rounded-lg font-semibold"
                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                            Connect Wallet
                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                      <div className="flex flex-col items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                    onClick={openAccountModal}
                                                                                                                                                                                                                                                                                                                                                                                    className="bg-white text-black px-4 py-2 rounded-lg flex items-center gap-2 font-medium"
                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="w-3 h-3 rounded-full bg-green-500"></span>
                                                                                                                                                                                                                                                                                                                                                                                           {account.displayName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-gray-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {isLoading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? "Loading balance..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : `${Number(balance?.formatted ?? 0).toFixed(4)} ${balance?.symbol ?? "USDC"}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={openChainModal}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="text-blue-400 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {chain.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ConnectButton.Custom>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }